export enum EMensagem {
  AtualizadoSucesso = 'Atualizado com sucesso',
  DesativadoSucesso = 'Desativado com sucesso',
  ErroComunicacaoGrpcUsuario = 'Erro ao conectar ao gRPC de usuário',
  ErroExportarPDF = 'Erro ao exportar PDF',
  ExcluidoSucesso = 'Excluído com sucesso',
  FilterInvalido = 'Filter inválido',
  IDsDiferentes = 'IDs diferentes',
  ImpossivelAlterar = 'Impossivel alterar',
  IniciadoGeracaoPDF = 'Iniciado geração PDF',
  MaisCaracteresPermitido = 'Contém mais caracteres do que o permitido',
  NaoPodeSerVazio = 'Não pode ser vazio',
  NaoValido = 'Não é válido',
  OrderInvalido = 'Order inválido',
  SalvoSucesso = 'Salvo com sucesso',
  UsuarioNaoIdentificado = 'Usuário não identificado',
}
